[FAB-6612] Handle Windows tempdir in node-sdk test
This CR escapes the filepath used for the debug logger on
Windows so that HFC_LOGGING contains properly formatted JSON
and can be parsed successfully.

Before:
$ gulp test-headless
...
[17:15:43] Starting 'test-headless'...
[17:15:43] Starting 'test-headless'...
warn: Failed to parse environment variable "HFC_LOGGING". Returned
 a winston logger with default configurations. Error:
SyntaxError: Unexpected token U in JSON at position 13
    at Object.parse (native)
...

$ ll ~/AppData/Local/Temp/hfc/test-log/debug.log
-rwx------+ 1 lehors None 0 Oct 13 17:15 /home/lehors/AppData/Local
/Temp/hfc/test-log/debug.log

After:
$ gulp test-headless
...
[17:17:34] Starting 'test-headless'...

TAP version 13

*** BlockDecoder test for readwrite sets
ok 1 Successfully build a results proto with read and write sets
...

$ ll ~/AppData/Local/Temp/hfc/test-log/debug.log
-rw-r--r-- 1 lehors 197121 462970 Oct 13 17:18 /c/Users/lehors/AppD
ata/Local/Temp/hfc/test-log/debug.log

This CR also fixes a typo in the fabric-ca-client tests.

Change-Id: Ia767aa135eb8803608de0322d7e4675326026b08
Signed-off-by: Arnaud J Le Hors <lehors@us.ibm.com>